# Indexation des documents
indexation:
  chunk_size: 500
  chunk_overlap: 50
  embedding_model: "sentence-transformers/all-mpnet-base-v2"
  persist_dir: "./chroma_langchain_db"
  data_dir: "./data"

# Synthèse du contexte
synthesizer:
  max_chunk_size: 500
  intro_message: "Voici les extraits les plus pertinents trouvés dans les documents :"
  default_source: "document inconnu"
  default_page: "page inconnue"
  score_precision: 3
  
# Modèle LLM
llm:
  model: "mistralai/mistral-7b-instruct:free"
  temperature: 0.1
  base_url: "https://openrouter.ai/api/v1"
  api_key_env: "OPENROUTER_API_KEY"

# RAG et Chatbot
rag:
  max_history: 5
  k_retrieve: 4

# Évaluation
evaluator:
  embed_model: "all-mpnet-base-v2"

# Chemins
paths:
  data: "./data"
  vectorstore: "./chroma_langchain_db"
  env_file: "file.env"




